In [2]:
!pip3 install numpy

In [3]:
import numpy as np

In [5]:
a=np.arange(21)

In [6]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [15]:
a[2:21:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
a[3:21:3]

array([ 3,  6,  9, 12, 15, 18])